build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -120,18 +120,24 @@ jobs:
           # Configure Git for merging
           git config --global user.email "q543069760@gmail.com"
           git config --global user.name "Build"
-          
+    
           # Add the Google BBR repository as a remote
           git remote add google-bbr https://github.com/google/bbr.git
-          git fetch google-bbr v3 --depth=1          
-          # Cherry-pick or merge only the tcp_bbr.c file
-          git checkout google-bbr/v3 -- net/ipv4/tcp_bbr.c          
-          # Add the file to the current branch and commit the changes
-          git add net/ipv4/tcp_bbr.c
-          git commit -m "Merge tcp_bbr.c from Google BBR v3 into kernel"          
+          git fetch google-bbr v3 --depth=1
+
+          # Check if the file exists in the repository
+          FILE_PATH="net/ipv4/tcp_bbr.c"
+          if git ls-remote google-bbr | grep -q "$FILE_PATH"; then
+          echo "File exists. Proceeding to fetch and merge..."
+          git checkout google-bbr/v3 -- $FILE_PATH
+          git add $FILE_PATH
+          git commit -m "Merge tcp_bbr.c from Google BBR v3 into kernel"
           echo "Successfully merged tcp_bbr.c into the kernel source."
-          sed -i 's/^\([[:space:]]*\)\.name[[:space:]]*=[[:space:]]*"bbr",/\1.name = "bbr3",/' ./common/net/ipv4/tcp_bbr.c
-      
+          else
+          echo "Error: File '$FILE_PATH' does not exist in the branch 'v3' of the Google BBR repository."
+          exit 1
+          fi
+          
       - name: Add KernelSU
         run: |
           echo "Changing to configuration directory: $CONFIG..."
